service: cambridge-tracker-progress
frameworkVersion: '3'

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs22.x
  region: ${file(serverless.env.yml):${opt:stage, 'dev'}.REGION, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--stack-trace-limit=1000'
    DATABASE_URL: ${file(serverless.env.yml):${opt:stage, 'dev'}.DATABASE_URL}
    JWT_SECRET: ${file(serverless.env.yml):${opt:stage, 'dev'}.JWT_SECRET}
    JWT_EXPIRES_IN: ${file(serverless.env.yml):${opt:stage, 'dev'}.JWT_EXPIRES_IN}

functions:
  progressMetrics:
    handler: src/controllers/progressController.getMetrics
    events:
      - httpApi:
          path: /metrics
          method: GET

  progressPracticePartMetrics:
    handler: src/controllers/progressController.getPracticePartMetrics
    events:
      - httpApi:
          path: /metrics/practice/parts
          method: GET

  progressWritingMetrics:
    handler: src/controllers/progressController.getWritingMetrics
    events:
      - httpApi:
          path: /metrics/writing
          method: GET

  progressScoreEvolution:
    handler: src/controllers/progressController.getScoreEvolution
    events:
      - httpApi:
          path: /metrics/score-evolution
          method: GET

package:
  individually: true

custom:
  esbuild: ${file(main.serverless.yml):custom.esbuild}
